### PR TITLE
Adding modal

### PR DESCRIPTION
**Pull request by nevah-evans**
Adding modal to webpage as well as replacing some CSS with bootstrap styling. Conflict in functional code for form and modal

### CODE REVIEW

**Review by SDKwapis — CHANGES_REQUESTED** [review]
When we add 'prevent default' to the javascript once the api is connected it will prevent the modal from closing. For now we can add this to the html and it will allow the modal to stay open so we can work on it:                     <script>
                        document.getElementById("riskyBtn").addEventListener("click", function(event){
                          event.preventDefault()
                        });
                        </script>

**Comment by Chris21789** [comment]
This works well in the coding review and looks good to merge. If there are problems with the form data we can review and change that after merge.

**Review by Chris21789 — APPROVED** [review]
This works well in the coding review and looks good to merge. If there are problems with the form data we can review and change that after merge.

**Review by CheyenneHamilton — APPROVED** [review]
Works well.

**Review by jahdona — COMMENTED** [review]
This seem to be perfect and could be merged. In case of functionality issues we could review accordingly.

**Review by SDKwapis — APPROVED** [review]

**Review by jahdona — COMMENTED** [review]
Good to be merged

**Pull request merged**
